name: C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: check compiler
      run: g++ --version
    - name: compile
      run: g++ -Wall -Werror -Wextra -std=c++20 -o main main.cpp ./include/Task.h ./include/TaskManager.h ./include/magic_enum/magic_enum.hpp ./src/TaskManager.cpp
    - name: check execution file
      run: ls -l main
