name: CMake Build for Task-Manager

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Cache cmake build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
            ${{ runner.os }}-cmake-

    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_MAKE_PROGRAM=/home/runner/work/_temp/-251648691/ninja

    - name: Build
      run: cmake --build build 

