name: CMake Build for Task-Manager

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Configure CMake
      run: cmake -B build -G Ninja

    - name: Build
      run: cmake --build build --parallel $(nproc)

